name: Deploy Azure Bicep

on:

  workflow_dispatch:

permissions:
  contents: read

env: 
  RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_SP_OBJECT_ID: ${{ vars.AZURE_SP_OBJECT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v3.0.2
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Service Principal Roles
        run: | 
          az role assignment list \
            --assignee ${{ env.AZURE_SP_OBJECT_ID }} \
            --scope /subscriptions/${{ env.AZURE_SUBSCRIPTION_ID }} \
            --output table
                  
      - name: Azure Bicep Deployment
        working-directory: ./infra
        run: |
          az deployment sub create \
            --location eastus2 \
            --template-file main.bicep