name: Deploy Azure Bicep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
permissions:
  contents: read

env: 
  RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  # AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v3.0.2
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Create Deployment at Subscription
      #   working-directory: '${{ github.workspace }}/infra'
      #   run: |
      #     az deployment sub create -f ./main.bicep --location eastus2

      - name: Azure Bicep Deployment
        working-directory: '${{ github.workspace}}/infra'
        run: |
          az deployment sub create \
            --location eastus2 \
            --template-file ../infra/main.bicep